server.port=8120
spring.application.name=service-oss
spring.profiles.active=dev
#aliyun.oss.file.end_point=oss-cn-beijing.aliyuncs.com
##aliyun.oss.file.key_id=LTAI5t81C147pxxzXhGwQmqH
#aliyun.oss.file.key_id=LTAI5tKM5isEqHx66p54St1C
##aliyun.oss.file.key_secret=cKLEfPlQT07o8TlmDDqzfdYCw3rDxn
#aliyun.oss.file.key_secret=3rzJdt8QSK5M9nagPbvPYesJSLH91L
#aliyun.oss.file.bucket_name=coursera-class
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.cloud.nacos.discovery.server-addr=10.221.173.121:8848
spring.cloud.nacos.discovery.watch.enabled=false
#local.upload.path=E:/Backups/Data/coursera
local.upload.path=/data/coursera
