spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.188.3:3306/coursera?serverTimezone=UTC&useSSL=false
    username: root
    password: Big0try92.
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      maxLifetime: 1800000      # 小于 MySQL wait_timeout
      connectionTimeout: 30000
      validationTimeout: 5000
      leakDetectionThreshold: 60000
      connectionTestQuery: SELECT 1

tencent:
  msm:
    secret_id: 1401044877
    secret_key: 709cb32a183416d2314b3a5dcb1cdc11
    end_point: sms.tencentcloudapi.com
    app_id: 1401044877
    template_id: 1401044877
    sign_name: coursera-class
