server.port=8160
spring.application.name=service-ucenter
# \u73AF\u5883\u914D\u7F6E
spring.profiles.active=dev
# mysql \u914D\u7F6E
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://47.120.68.25:3306/coursera?serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=root
spring.datasource.password=Big0try92.

spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.idleTimeout=600000
# MySQL wait_timeout
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000
spring.datasource.hikari.leakDetectionThreshold=60000
spring.datasource.hikari.connectionTestQuery=SELECT 1

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT-8

mybatis-plus.mapper-locations=classpath:com/zh/oes/ucenter/mapper/xml/*.xml
mybatis-plus.type-aliases-package=com.zh.oes.model.entity.ucenter,com.zh.oes.model.entity.app
# nacos \u5730\u5740
spring.cloud.nacos.discovery.server-addr=47.120.68.25:8848
# \u7981\u7528\u624B\u8868
spring.cloud.nacos.discovery.watch.enabled=false
# redis \u914D\u7F6E
spring.redis.host=47.120.68.25
spring.redis.port=6379
spring.redis.password=Big0try92.
spring.redis.database=0
spring.redis.timeout=1800000
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=-1

spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=0
# \u5FAE\u4FE1\u5546\u6237
wx.open.app_id=wxed9954c01bb89b47
wx.open.app_secret=a7482517235173ddb4083788de60b90e
wx.open.redirect_url=http://localhost:8160/api/ucenter/wx/callback
